server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/JAVAYH/cloud-config-center-3344.git
          search-paths:
            - cloud-config-center-3344
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://10.10.63.205:8861/eureka